// Code generated by hack/karpenter-sync; DO NOT EDIT.

package addon

import rbacv1 "k8s.io/api/rbac/v1"

func karpenterClusterRules() []rbacv1.PolicyRule {
	return []rbacv1.PolicyRule{
		{APIGroups: []string{"karpenter.sh"}, Resources: []string{"nodepools", "nodepools/status", "nodeclaims", "nodeclaims/status", "nodeoverlays", "nodeoverlays/status"}, Verbs: []string{"get", "list", "watch"}},
		{APIGroups: []string{""}, Resources: []string{"pods", "nodes", "persistentvolumes", "persistentvolumeclaims", "replicationcontrollers", "namespaces"}, Verbs: []string{"get", "list", "watch"}},
		{APIGroups: []string{"storage.k8s.io"}, Resources: []string{"storageclasses", "csinodes", "volumeattachments"}, Verbs: []string{"get", "watch", "list"}},
		{APIGroups: []string{"apps"}, Resources: []string{"daemonsets", "deployments", "replicasets", "statefulsets"}, Verbs: []string{"list", "watch"}},
		{APIGroups: []string{"policy"}, Resources: []string{"poddisruptionbudgets"}, Verbs: []string{"get", "list", "watch"}},
		{APIGroups: []string{""}, Resources: []string{"events"}, Verbs: []string{"get", "list", "watch"}},
		{APIGroups: []string{"karpenter.sh"}, Resources: []string{"nodeclaims", "nodeclaims/status"}, Verbs: []string{"create", "delete", "update", "patch"}},
		{APIGroups: []string{"karpenter.sh"}, Resources: []string{"nodepools", "nodepools/status", "nodeoverlays/status"}, Verbs: []string{"update", "patch"}},
		{APIGroups: []string{""}, Resources: []string{"events"}, Verbs: []string{"create", "patch"}},
		{APIGroups: []string{""}, Resources: []string{"nodes"}, Verbs: []string{"patch", "delete", "update"}},
		{APIGroups: []string{""}, Resources: []string{"pods/eviction"}, Verbs: []string{"create"}},
		{APIGroups: []string{""}, Resources: []string{"pods"}, Verbs: []string{"delete"}},
		{APIGroups: []string{"karpenter.k8s.aws"}, Resources: []string{"ec2nodeclasses"}, Verbs: []string{"get", "list", "watch"}},
		{APIGroups: []string{"karpenter.k8s.aws"}, Resources: []string{"ec2nodeclasses", "ec2nodeclasses/status"}, Verbs: []string{"patch", "update"}},
	}
}

func karpenterControllerRoleRules() []rbacv1.PolicyRule {
	return []rbacv1.PolicyRule{
		{APIGroups: []string{"coordination.k8s.io"}, Resources: []string{"leases"}, Verbs: []string{"get", "watch"}},
		{APIGroups: []string{"coordination.k8s.io"}, Resources: []string{"leases"}, Verbs: []string{"patch", "update"}, ResourceNames: []string{"karpenter-leader-election"}},
		{APIGroups: []string{"coordination.k8s.io"}, Resources: []string{"leases"}, Verbs: []string{"create"}},
	}
}

func karpenterDNSRoleRules() []rbacv1.PolicyRule {
	return []rbacv1.PolicyRule{
		{APIGroups: []string{""}, Resources: []string{"services"}, Verbs: []string{"get"}, ResourceNames: []string{"kube-dns"}},
	}
}
