apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-provider-aws-addon-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: karpenter-provider-aws-addon
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter-provider-aws-addon
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karpenter-provider-aws-addon
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (print "v" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - hub
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
