package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	yamlv3 "gopkg.in/yaml.v3"
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/yaml"
)

const (
	chartRef = "oci://public.ecr.aws/karpenter/karpenter"

	generatedComment = "# Code generated by hack/karpenter-sync; DO NOT EDIT.\n"
	generatedGo      = "// Code generated by hack/karpenter-sync; DO NOT EDIT.\n"

	markerClusterName       = "__KARPENTER_CLUSTER_NAME__"
	markerClusterEndpoint   = "__KARPENTER_CLUSTER_ENDPOINT__"
	markerInterruptionQueue = "__KARPENTER_INTERRUPTION_QUEUE__"

	hostedManifestLocationKey = "addon.open-cluster-management.io/hosted-manifest-location"

	// yamlNestIndent is the per-level indent yaml.v3 SetIndent(2) uses for
	// nested children. The synthetic Helm template blocks below assume this
	// to lay out their own multi-level content; if yaml.v3's SetIndent value
	// changes here, update this constant in lockstep.
	yamlNestIndent = 2

	// Sentinel scalar values get inserted at the structured-map level and are
	// replaced after marshal by applySentinels. Their indent is read from the
	// emitted line, so the replacement adapts automatically to yaml.v3's
	// formatting rules.
	sentinelHostedLabel = "__KARPENTER_SYNC_HOSTED_LABEL__"
	sentinelIQWrapBegin = "__KARPENTER_SYNC_INTERRUPTION_QUEUE_BEGIN__"
	sentinelIQWrapEnd   = "__KARPENTER_SYNC_INTERRUPTION_QUEUE_END__"

	sentinelEnvAnchor        = "env:"
	sentinelContainersAnchor = "containers:"
	sentinelPortsAnchor      = "ports:"
)

type options struct {
	repoRoot string
	version  string
	helm     string
}

type manifestDoc struct {
	raw    string
	object *unstructured.Unstructured
}

func main() {
	opts := options{}
	flag.StringVar(&opts.repoRoot, "repo-root", ".", "repository root to write generated files into")
	flag.StringVar(&opts.version, "version", envOrDefault("KARPENTER_VERSION", "1.12.1"), "upstream Karpenter chart version")
	flag.StringVar(&opts.helm, "helm", envOrDefault("HELM", "helm"), "helm executable")
	flag.Parse()

	if err := run(opts); err != nil {
		fmt.Fprintf(os.Stderr, "karpenter-sync: %v\n", err)
		os.Exit(1)
	}
}

func run(opts options) error {
	rendered, err := renderChart(opts)
	if err != nil {
		return err
	}
	docs, err := parseDocuments(rendered)
	if err != nil {
		return err
	}
	if err := removeGeneratedFiles(opts.repoRoot); err != nil {
		return err
	}
	if err := writeCRDs(opts.repoRoot, docs); err != nil {
		return err
	}

	serviceAccount, err := transformServiceAccount(findObject(docs, "ServiceAccount", "karpenter"))
	if err != nil {
		return err
	}
	if err := writeFile(opts.repoRoot, "pkg/addon/manifests/templates/01-hosting-serviceaccount.yaml", serviceAccount); err != nil {
		return err
	}

	service, err := transformService(findObject(docs, "Service", "karpenter"))
	if err != nil {
		return err
	}
	if err := writeFile(opts.repoRoot, "pkg/addon/manifests/templates/02-hosting-service.yaml", service); err != nil {
		return err
	}

	pdb, err := transformPDB(findObject(docs, "PodDisruptionBudget", "karpenter"))
	if err != nil {
		return err
	}
	if err := writeFile(opts.repoRoot, "pkg/addon/manifests/templates/03-hosting-pdb.yaml", pdb); err != nil {
		return err
	}

	deploymentDoc := findObject(docs, "Deployment", "karpenter")
	deployment, _, err := transformDeployment(deploymentDoc)
	if err != nil {
		return err
	}
	if err := writeFile(opts.repoRoot, "pkg/addon/manifests/templates/04-hosting-deployment.yaml", deployment); err != nil {
		return err
	}

	generatedRBAC, err := renderGeneratedGo(docs)
	if err != nil {
		return err
	}
	return writeFile(opts.repoRoot, "pkg/addon/karpenter_generated.go", generatedRBAC)
}

func renderChart(opts options) (string, error) {
	args := []string{
		"template", "karpenter", chartRef,
		"--version", opts.version,
		"--namespace", "kube-system",
		"--include-crds",
		"--set-string", "settings.clusterName=" + markerClusterName,
		"--set-string", "settings.clusterEndpoint=" + markerClusterEndpoint,
		"--set-string", "settings.interruptionQueue=" + markerInterruptionQueue,
	}
	cmd := exec.Command(opts.helm, args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("render upstream chart: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return string(out), nil
}

func parseDocuments(rendered string) ([]manifestDoc, error) {
	rawDocs := splitYAMLDocuments(rendered)
	docs := make([]manifestDoc, 0, len(rawDocs))
	for _, raw := range rawDocs {
		var obj unstructured.Unstructured
		if err := yaml.NewYAMLOrJSONDecoder(strings.NewReader(raw), 4096).Decode(&obj); err != nil {
			return nil, fmt.Errorf("decode upstream manifest: %w", err)
		}
		if len(obj.Object) == 0 {
			continue
		}
		docs = append(docs, manifestDoc{
			raw:    strings.TrimSpace(raw),
			object: &obj,
		})
	}
	return docs, nil
}

func splitYAMLDocuments(rendered string) []string {
	var docs []string
	var current strings.Builder
	flush := func() {
		doc := strings.TrimSpace(current.String())
		if doc != "" {
			docs = append(docs, doc)
		}
		current.Reset()
	}
	for _, line := range strings.Split(rendered, "\n") {
		if strings.TrimSpace(line) == "---" {
			flush()
			continue
		}
		current.WriteString(line)
		current.WriteByte('\n')
	}
	flush()
	return docs
}

func removeGeneratedFiles(repoRoot string) error {
	paths := []string{
		"pkg/addon/karpenter_generated.go",
		"pkg/addon/manifests/templates/crds",
		"pkg/addon/manifests/templates/01-hosting-serviceaccount.yaml",
		"pkg/addon/manifests/templates/02-hosting-service.yaml",
		"pkg/addon/manifests/templates/03-hosting-pdb.yaml",
		"pkg/addon/manifests/templates/04-hosting-deployment.yaml",
	}
	for _, path := range paths {
		if err := os.RemoveAll(filepath.Join(repoRoot, path)); err != nil {
			return err
		}
	}
	return nil
}

func writeCRDs(repoRoot string, docs []manifestDoc) error {
	var crds []manifestDoc
	for _, doc := range docs {
		if doc.object.GetKind() == "CustomResourceDefinition" {
			crds = append(crds, doc)
		}
	}
	sort.SliceStable(crds, func(i, j int) bool {
		return crds[i].object.GetName() < crds[j].object.GetName()
	})
	for i, doc := range crds {
		path := fmt.Sprintf("pkg/addon/manifests/templates/crds/20-target-karpenter-crd-%02d.yaml", i+1)
		if err := writeFile(repoRoot, path, generatedComment+doc.raw+"\n"); err != nil {
			return err
		}
	}
	return nil
}

func findObject(docs []manifestDoc, kind, name string) manifestDoc {
	for _, doc := range docs {
		if doc.object.GetKind() == kind && doc.object.GetName() == name {
			return doc
		}
	}
	return manifestDoc{}
}

func transformServiceAccount(doc manifestDoc) (string, error) {
	obj, err := copyRequiredObject(doc, "ServiceAccount/karpenter")
	if err != nil {
		return "", err
	}
	if err := setResourceMetadata(obj.Object, "{{ .ServiceAccountName }}"); err != nil {
		return "", err
	}
	return marshalGeneratedYAML(obj.Object)
}

func transformService(doc manifestDoc) (string, error) {
	obj, err := copyRequiredObject(doc, "Service/karpenter")
	if err != nil {
		return "", err
	}
	if err := setResourceMetadata(obj.Object, "{{ .DeploymentName }}"); err != nil {
		return "", err
	}
	spec, err := mapAt(obj.Object, "spec")
	if err != nil {
		return "", err
	}
	spec["selector"] = selectorLabels()
	return marshalGeneratedYAML(obj.Object)
}

func transformPDB(doc manifestDoc) (string, error) {
	obj, err := copyRequiredObject(doc, "PodDisruptionBudget/karpenter")
	if err != nil {
		return "", err
	}
	if err := setResourceMetadata(obj.Object, "{{ .DeploymentName }}"); err != nil {
		return "", err
	}
	selector, err := mapAt(obj.Object, "spec", "selector")
	if err != nil {
		return "", err
	}
	selector["matchLabels"] = selectorLabels()
	return marshalGeneratedYAML(obj.Object)
}

func transformDeployment(doc manifestDoc) (string, string, error) {
	obj, err := copyRequiredObject(doc, "Deployment/karpenter")
	if err != nil {
		return "", "", err
	}
	if err := setResourceMetadata(obj.Object, "{{ .DeploymentName }}"); err != nil {
		return "", "", err
	}
	rewriteUpstreamLabelValues(obj.Object)

	selector, err := mapAt(obj.Object, "spec", "selector")
	if err != nil {
		return "", "", err
	}
	selector["matchLabels"] = selectorLabels()

	templateMeta, err := mapAt(obj.Object, "spec", "template", "metadata")
	if err != nil {
		return "", "", err
	}
	templateMeta["labels"] = podLabels()
	if annotations, ok := templateMeta["annotations"].(map[string]interface{}); !ok || len(annotations) == 0 {
		delete(templateMeta, "annotations")
	}

	podSpec, err := mapAt(obj.Object, "spec", "template", "spec")
	if err != nil {
		return "", "", err
	}
	podSpec["serviceAccountName"] = "{{ .ServiceAccountName }}"

	containers, err := sliceAt(podSpec, "containers")
	if err != nil {
		return "", "", err
	}
	if len(containers) != 1 {
		return "", "", fmt.Errorf("expected upstream deployment to have one controller container, got %d", len(containers))
	}
	container, ok := containers[0].(map[string]interface{})
	if !ok {
		return "", "", errors.New("upstream controller container is not an object")
	}
	image, _ := container["image"].(string)
	if image == "" {
		return "", "", errors.New("upstream controller image is empty")
	}
	container["name"] = "{{ .KarpenterContainerName }}"
	container["image"] = "{{ .KarpenterImage }}"
	if err := transformEnv(container); err != nil {
		return "", "", err
	}

	out, err := marshalGeneratedYAML(obj.Object)
	if err != nil {
		return "", "", err
	}
	out, err = injectHostedDeploymentBlocks(out)
	if err != nil {
		return "", "", err
	}
	return out, image, nil
}

func copyRequiredObject(doc manifestDoc, name string) (*unstructured.Unstructured, error) {
	if doc.object == nil || len(doc.object.Object) == 0 {
		return nil, fmt.Errorf("upstream %s not found", name)
	}
	return doc.object.DeepCopy(), nil
}

func setResourceMetadata(obj map[string]interface{}, name string) error {
	metadata, err := mapAt(obj, "metadata")
	if err != nil {
		return err
	}
	metadata["name"] = name
	metadata["namespace"] = "{{ .AddonInstallNamespace }}"
	metadata["labels"] = resourceLabels()
	delete(metadata, "annotations")
	return nil
}

func resourceLabels() map[string]interface{} {
	labels := podLabels()
	labels[hostedManifestLocationKey] = sentinelHostedLabel
	return labels
}

func podLabels() map[string]interface{} {
	return map[string]interface{}{
		"app.kubernetes.io/name":       "{{ .AddonName }}",
		"app.kubernetes.io/instance":   "{{ .DeploymentName }}",
		"app.kubernetes.io/managed-by": "karpenter-provider-aws-addon",
	}
}

func selectorLabels() map[string]interface{} {
	return map[string]interface{}{
		"app.kubernetes.io/name":     "{{ .AddonName }}",
		"app.kubernetes.io/instance": "{{ .DeploymentName }}",
	}
}

func rewriteUpstreamLabelValues(value interface{}) {
	switch typed := value.(type) {
	case map[string]interface{}:
		for key, item := range typed {
			if s, ok := item.(string); ok {
				switch key {
				case "app.kubernetes.io/name":
					if s == "karpenter" {
						typed[key] = "{{ .AddonName }}"
					}
				case "app.kubernetes.io/instance":
					if s == "karpenter" {
						typed[key] = "{{ .DeploymentName }}"
					}
				}
			}
			rewriteUpstreamLabelValues(item)
		}
	case []interface{}:
		for _, item := range typed {
			rewriteUpstreamLabelValues(item)
		}
	}
}

func transformEnv(container map[string]interface{}) error {
	env, err := sliceAt(container, "env")
	if err != nil {
		return err
	}
	out := make([]interface{}, 0, len(env)+2)
	insertedRegion := false
	for _, item := range env {
		envVar, ok := item.(map[string]interface{})
		if !ok {
			return errors.New("upstream env item is not an object")
		}
		name, _ := envVar["name"].(string)
		if name == "CLUSTER_NAME" && !insertedRegion {
			out = append(out, awsRegionEnv()...)
			insertedRegion = true
		}
		switch name {
		case "KARPENTER_SERVICE":
			envVar["value"] = "{{ .DeploymentName }}"
		case "CLUSTER_NAME":
			envVar["value"] = "{{ .KarpenterClusterName }}"
		case "CLUSTER_ENDPOINT":
			envVar["value"] = "{{ .ClusterEndpoint }}"
		case "INTERRUPTION_QUEUE":
			envVar["value"] = "{{ .InterruptionQueue }}"
			rewriteContainerNameResourceRef(envVar)
			out = append(out, map[string]interface{}{"name": sentinelIQWrapBegin})
			out = append(out, envVar)
			out = append(out, map[string]interface{}{"name": sentinelIQWrapEnd})
			continue
		}
		rewriteContainerNameResourceRef(envVar)
		out = append(out, envVar)
	}
	if !insertedRegion {
		out = append(out, awsRegionEnv()...)
	}
	container["env"] = out
	return nil
}

func awsRegionEnv() []interface{} {
	return []interface{}{
		map[string]interface{}{
			"name":  "AWS_REGION",
			"value": "{{ .AWSRegion }}",
		},
		map[string]interface{}{
			"name":  "AWS_DEFAULT_REGION",
			"value": "{{ .AWSRegion }}",
		},
	}
}

func rewriteContainerNameResourceRef(envVar map[string]interface{}) {
	valueFrom, ok := envVar["valueFrom"].(map[string]interface{})
	if !ok {
		return
	}
	resourceFieldRef, ok := valueFrom["resourceFieldRef"].(map[string]interface{})
	if !ok {
		return
	}
	if _, ok := resourceFieldRef["containerName"]; ok {
		resourceFieldRef["containerName"] = "{{ .KarpenterContainerName }}"
	}
}

// injectHostedDeploymentBlocks rewrites the marshalled Deployment YAML to:
//   - expand single-line sentinel scalars into Helm conditionals
//     ({{- if eq .InstallMode "Hosted" }} ... {{- end }})
//   - wrap the INTERRUPTION_QUEUE env item (marked with sentinelIQWrapMark)
//     in {{- if .InterruptionQueue }} ... {{- end }} and strip the marker line
//   - insert the hosted env / pod / volumeMounts blocks at their anchor keys
//
// Indents are derived from the actual rendered YAML lines (not hardcoded math),
// so the output absorbs yaml.v3's formatting rules naturally.
func injectHostedDeploymentBlocks(in string) (string, error) {
	out, err := wrapInterruptionQueueEnv(in)
	if err != nil {
		return "", err
	}
	out, err = insertAfterAnchorList(out, sentinelEnvAnchor, hostedEnvLines)
	if err != nil {
		return "", err
	}
	out, err = insertBeforeAnchorMap(out, sentinelContainersAnchor, hostedPodLines)
	if err != nil {
		return "", err
	}
	out, err = insertBeforeAnchorMap(out, sentinelPortsAnchor, hostedContainerVolumeMountsLines)
	if err != nil {
		return "", err
	}
	return out, nil
}

// applySentinels expands single-line scalar sentinels embedded in the rendered
// YAML. Today this handles only sentinelHostedLabel, which becomes a three-line
// conditional wrapping the label.
func applySentinels(in string) string {
	lines := strings.Split(in, "\n")
	out := make([]string, 0, len(lines)+4)
	for _, line := range lines {
		trimmed := strings.TrimLeft(line, " ")
		if strings.HasPrefix(trimmed, hostedManifestLocationKey+":") && strings.Contains(line, sentinelHostedLabel) {
			indent := line[:len(line)-len(trimmed)]
			out = append(out,
				`{{- if eq .InstallMode "Hosted" }}`,
				indent+hostedManifestLocationKey+": hosting",
				`{{- end }}`,
			)
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// wrapInterruptionQueueEnv finds the sentinel marker env items emitted around
// the INTERRUPTION_QUEUE entry, replaces them with the matching
// {{- if .InterruptionQueue }} / {{- end }} directives, and unindents the
// directives one nesting level to match the parent list indent.
func wrapInterruptionQueueEnv(in string) (string, error) {
	lines := strings.Split(in, "\n")
	beginIdx, endIdx := -1, -1
	for i, line := range lines {
		switch {
		case beginIdx == -1 && strings.Contains(line, "name: "+sentinelIQWrapBegin):
			beginIdx = i
		case beginIdx != -1 && strings.Contains(line, "name: "+sentinelIQWrapEnd):
			endIdx = i
		}
	}
	if beginIdx == -1 || endIdx == -1 {
		return "", errors.New("INTERRUPTION_QUEUE wrap sentinels not found in upstream deployment")
	}
	lines[beginIdx] = `{{- if .InterruptionQueue }}`
	lines[endIdx] = `{{- end }}`
	return strings.Join(lines, "\n"), nil
}

// insertAfterAnchorList finds the line matching `<indent>... anchor` (anchor is
// a YAML key that introduces a list, e.g. `env:`), then derives the list-item
// indent from the actual line below the anchor and inserts the rendered block
// using that derived indent.
func insertAfterAnchorList(in, anchor string, render func(itemIndent string) []string) (string, error) {
	lines := strings.Split(in, "\n")
	anchorIdx := -1
	for i, line := range lines {
		if hasKeySuffix(line, anchor) {
			anchorIdx = i
			break
		}
	}
	if anchorIdx == -1 {
		return "", fmt.Errorf("anchor %q not found in deployment YAML", anchor)
	}
	itemIndent, ok := findFollowingItemIndent(lines, anchorIdx)
	if !ok {
		return "", fmt.Errorf("could not derive list-item indent below anchor %q", anchor)
	}
	out := append([]string{}, lines[:anchorIdx+1]...)
	out = append(out, render(itemIndent)...)
	out = append(out, lines[anchorIdx+1:]...)
	return strings.Join(out, "\n"), nil
}

// insertBeforeAnchorMap inserts the rendered block immediately before the line
// matching `<indent>anchor`. The block is rendered with the captured indent.
func insertBeforeAnchorMap(in, anchor string, render func(keyIndent string) []string) (string, error) {
	lines := strings.Split(in, "\n")
	anchorIdx := -1
	for i, line := range lines {
		if hasKeySuffix(line, anchor) && !strings.HasPrefix(strings.TrimLeft(line, " "), "- ") {
			anchorIdx = i
			break
		}
	}
	if anchorIdx == -1 {
		return "", fmt.Errorf("anchor %q not found in deployment YAML", anchor)
	}
	keyIndent := leadingWhitespace(lines[anchorIdx])
	out := append([]string{}, lines[:anchorIdx]...)
	out = append(out, render(keyIndent)...)
	out = append(out, lines[anchorIdx:]...)
	return strings.Join(out, "\n"), nil
}

func hasKeySuffix(line, anchor string) bool {
	trimmed := strings.TrimRight(strings.TrimLeft(line, " "), " ")
	if strings.HasPrefix(trimmed, "- ") {
		trimmed = strings.TrimPrefix(trimmed, "- ")
	}
	return trimmed == anchor
}

func leadingWhitespace(line string) string {
	return line[:len(line)-len(strings.TrimLeft(line, " "))]
}

func findFollowingItemIndent(lines []string, anchorIdx int) (string, bool) {
	for i := anchorIdx + 1; i < len(lines); i++ {
		trimmed := strings.TrimLeft(lines[i], " ")
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "- ") {
			return lines[i][:len(lines[i])-len(trimmed)], true
		}
		return "", false
	}
	return "", false
}

func hostedEnvLines(itemIndent string) []string {
	return []string{
		`{{- if eq .InstallMode "Hosted" }}`,
		itemIndent + `- name: KUBECONFIG`,
		itemIndent + `  value: {{ .ManagedKubeconfigPath }}`,
		itemIndent + `- name: AWS_CONFIG_FILE`,
		itemIndent + `  value: {{ .AWSConfigPath }}`,
		itemIndent + `- name: AWS_SDK_LOAD_CONFIG`,
		itemIndent + `  value: "1"`,
		`{{- end }}`,
	}
}

func hostedPodLines(keyIndent string) []string {
	item := keyIndent + strings.Repeat(" ", yamlNestIndent)
	sub := item + strings.Repeat(" ", yamlNestIndent)
	return []string{
		`{{- if eq .InstallMode "Hosted" }}`,
		keyIndent + `volumes:`,
		item + `- name: {{ .AWSIRSAStateVolumeName }}`,
		sub + `emptyDir: {}`,
		item + `- name: {{ .ManagedKubeconfigVolumeName }}`,
		sub + `secret:`,
		sub + `  secretName: {{ .ManagedKubeConfigSecret }}`,
		keyIndent + `initContainers:`,
		item + `- name: {{ .IRSASidecarContainerName }}`,
		sub + `image: {{ .IRSASidecarImage }}`,
		sub + `imagePullPolicy: IfNotPresent`,
		sub + `restartPolicy: Always`,
		sub + `command:`,
		sub + `  - /aws-irsa-sidecar`,
		sub + `args:`,
		sub + `  - --kubeconfig={{ .ManagedKubeconfigPath }}`,
		sub + `  - --token-file={{ .AWSTokenPath }}`,
		sub + `  - --aws-config-file={{ .AWSConfigPath }}`,
		sub + `startupProbe:`,
		sub + `  exec:`,
		sub + `    command:`,
		sub + `      - /aws-irsa-sidecar`,
		sub + `      - check`,
		sub + `      - --token-file={{ .AWSTokenPath }}`,
		sub + `      - --aws-config-file={{ .AWSConfigPath }}`,
		sub + `  periodSeconds: 2`,
		sub + `  failureThreshold: 90`,
		sub + `securityContext:`,
		sub + `  allowPrivilegeEscalation: false`,
		sub + `  capabilities:`,
		sub + `    drop:`,
		sub + `      - ALL`,
		sub + `volumeMounts:`,
		sub + `  - name: {{ .AWSIRSAStateVolumeName }}`,
		sub + `    mountPath: /var/run/aws-irsa`,
		sub + `  - name: {{ .ManagedKubeconfigVolumeName }}`,
		sub + `    mountPath: /managed/config`,
		sub + `    readOnly: true`,
		`{{- end }}`,
	}
}

func hostedContainerVolumeMountsLines(keyIndent string) []string {
	item := keyIndent + strings.Repeat(" ", yamlNestIndent)
	sub := item + strings.Repeat(" ", yamlNestIndent)
	return []string{
		`{{- if eq .InstallMode "Hosted" }}`,
		keyIndent + `volumeMounts:`,
		item + `- name: {{ .AWSIRSAStateVolumeName }}`,
		sub + `mountPath: /var/run/aws-irsa`,
		sub + `readOnly: true`,
		item + `- name: {{ .ManagedKubeconfigVolumeName }}`,
		sub + `mountPath: /managed/config`,
		sub + `readOnly: true`,
		`{{- end }}`,
	}
}

func renderGeneratedGo(docs []manifestDoc) (string, error) {
	clusterRules, err := collectClusterRoleRules(docs, []string{"karpenter-core", "karpenter"})
	if err != nil {
		return "", err
	}
	controllerRoleRules, err := collectRoleRules(docs, "karpenter")
	if err != nil {
		return "", err
	}
	dnsRoleRules, err := collectRoleRules(docs, "karpenter-dns")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(generatedGo)
	b.WriteString("\npackage addon\n\n")
	b.WriteString("import rbacv1 \"k8s.io/api/rbac/v1\"\n\n")
	writePolicyRulesFunc(&b, "karpenterClusterRules", clusterRules)
	writePolicyRulesFunc(&b, "karpenterControllerRoleRules", controllerRoleRules)
	writePolicyRulesFunc(&b, "karpenterDNSRoleRules", dnsRoleRules)
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}

func collectClusterRoleRules(docs []manifestDoc, names []string) ([]rbacv1.PolicyRule, error) {
	var out []rbacv1.PolicyRule
	for _, name := range names {
		doc := findObject(docs, "ClusterRole", name)
		if doc.object == nil {
			return nil, fmt.Errorf("upstream ClusterRole %q not found", name)
		}
		var role rbacv1.ClusterRole
		if err := runtime.DefaultUnstructuredConverter.FromUnstructured(doc.object.Object, &role); err != nil {
			return nil, fmt.Errorf("convert ClusterRole %q: %w", name, err)
		}
		out = append(out, role.Rules...)
	}
	return out, nil
}

func collectRoleRules(docs []manifestDoc, name string) ([]rbacv1.PolicyRule, error) {
	doc := findObject(docs, "Role", name)
	if doc.object == nil {
		return nil, fmt.Errorf("upstream Role %q not found", name)
	}
	var role rbacv1.Role
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(doc.object.Object, &role); err != nil {
		return nil, fmt.Errorf("convert Role %q: %w", name, err)
	}
	return role.Rules, nil
}

func writePolicyRulesFunc(b *strings.Builder, name string, rules []rbacv1.PolicyRule) {
	fmt.Fprintf(b, "func %s() []rbacv1.PolicyRule {\n", name)
	b.WriteString("\treturn []rbacv1.PolicyRule{\n")
	for _, rule := range rules {
		b.WriteString("\t\t{")
		fmt.Fprintf(b, "APIGroups: []string{%s}, ", quotedStrings(rule.APIGroups))
		fmt.Fprintf(b, "Resources: []string{%s}, ", quotedStrings(rule.Resources))
		fmt.Fprintf(b, "Verbs: []string{%s}", quotedStrings(rule.Verbs))
		if len(rule.ResourceNames) > 0 {
			fmt.Fprintf(b, ", ResourceNames: []string{%s}", quotedStrings(rule.ResourceNames))
		}
		if len(rule.NonResourceURLs) > 0 {
			fmt.Fprintf(b, ", NonResourceURLs: []string{%s}", quotedStrings(rule.NonResourceURLs))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func quotedStrings(values []string) string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, strconv.Quote(value))
	}
	return strings.Join(out, ", ")
}

func mapAt(root map[string]interface{}, path ...string) (map[string]interface{}, error) {
	current := root
	for _, field := range path {
		next, ok := current[field].(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf("field %s is not an object", strings.Join(path, "."))
		}
		current = next
	}
	return current, nil
}

func sliceAt(root map[string]interface{}, path ...string) ([]interface{}, error) {
	if len(path) == 0 {
		return nil, errors.New("slice path is empty")
	}
	parent, err := mapAt(root, path[:len(path)-1]...)
	if err != nil {
		return nil, err
	}
	value, ok := parent[path[len(path)-1]].([]interface{})
	if !ok {
		return nil, fmt.Errorf("field %s is not a list", strings.Join(path, "."))
	}
	return value, nil
}

func marshalGeneratedYAML(value interface{}) (string, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedComment)
	encoder := yamlv3.NewEncoder(&buf)
	encoder.SetIndent(yamlNestIndent)
	if err := encoder.Encode(value); err != nil {
		return "", err
	}
	if err := encoder.Close(); err != nil {
		return "", err
	}
	out := strings.TrimSuffix(buf.String(), "...\n")
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return applySentinels(out), nil
}

func writeFile(repoRoot, path, content string) error {
	fullPath := filepath.Join(repoRoot, path)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(fullPath, []byte(content), 0o644)
}

func envOrDefault(key, defaultValue string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return defaultValue
}
